_wandb:
    value:
        cli_version: 0.22.2
        e:
            n6b7o1ohf0wjxsdy7f9jikkg1hans0e7:
                args:
                    - --app
                    - .
                    - --num-supernodes
                    - "10"
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1081101176832"
                        used: "91667668992"
                email: nozzolillo01@gmail.com
                executable: /home/user/fl/venv/bin/python
                host: HP-Angelo
                memory:
                    total: "7977758720"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/user/fl/venv/bin/flower-simulation
                python: CPython 3.12.3
                root: /home/user/fl/my-app
                startedAt: "2025-10-15T10:31:18.352830Z"
                writerId: n6b7o1ohf0wjxsdy7f9jikkg1hans0e7
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 30
                - 41
                - 49
                - 51
            "2":
                - 1
                - 30
                - 41
                - 49
                - 51
            "3":
                - 13
                - 61
            "4": 3.12.3
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
